# Generated by Django 3.1.8 on 2023-07-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='laster_name',
            new_name='last_name',
        ),
    ]
